<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="show2.aspx.cs" Inherits="Lab_test.show2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server"> 
         
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Pass" HeaderText="Pass" SortExpression="Pass" />
            </Columns>
        </asp:GridView>
 
         
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:hello %>" ProviderName="<%$ ConnectionStrings:hello.ProviderName %>" 
            SelectCommand="SELECT * FROM [info]" 
            UpdateCommand="update info set Name=@Name, Email=@Email, Pass=@Pass where ID=@ID" 
            DeleteCommand="delete from info where ID=@ID" 
            > 
        </asp:SqlDataSource>
 
         
    </form>
</body>
</html>
